name: fcn
training_data_cls: GaussiandD2NL
N: 1024
# note that the mean/std values will be broadcasted across `in_features`
class_means: 
  - -2
  - 2
class_stds: 
  - 0.5
  - 0.5
class_sizes: 
  - 512
  - 512
batch_size: 1024
num_epochs: 1000
L: 2
in_features: 1
hidden_features: 2000
out_features: 1
num_classes: 2
use_batch_norm: false
lr: 0.0001
momentum: 0.0
weight_decay: 0.000001
bias_std: 0
hidden_weight_std: 1
final_weight_std: 1.97
activation: erf
probe_features: true
probe_kernels: false
probe_weights: true
probing_frequency: 1000
use_cache: true  # set it to False for discarding cache of data and models
